### ISSUE TITLE
Event Section

### ISSUE THREAD

**Issue by anitsingh367** [anitsingh367/LT-react-revamp#10]
- [x] It should have a heading at the top.
- [x] It should consist of multiple cards (max 8).
> - [x] Cards should have an Image, Title, Event Status, Short Description with max 3 lines, View Details, and a Share Button.
- [x] It should have a "View All" button that routes the user to the projects dashboard page.

Refer to the below design 
https://www.figma.com/file/kzMg2Y4R3XITupa0BQjsKP/Living-Treasure?node-id=26%3A264

**Comment by Rohitdhende** [comment]
This issue has been resolved. We can close this issue.
