### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by anitsingh367** [anitsingh367/LT-react-revamp#2]
- [x] Add image in card header 
- [x] Add Card Title along with status chips
- [x] Add Card Description
- [x] Add Card buttons 
- [x] Card Description should hold not more than 3 lines and should truncate with ellipsis after that.
> - [x]  View Details which opens a modal to enter details regarding the event

**Comment by Rohitdhende** [comment]
This issue has been resolved. We can close this issue.
