### ISSUE TITLE
Testimonial Carousel Section

### ISSUE THREAD

**Issue by anitsingh367** [anitsingh367/LT-react-revamp#3]
- [x] Add a testimonial carousel that contains all the testimonials according to the below design.
> ![image](https://user-images.githubusercontent.com/31277330/184504720-9166e281-ead6-4100-becc-9edce68f4e97.png)
- [x] Testimonial Carousel should be responsive to 3 breakpoints - Mobile, Tablet and Laptop

**Comment by atharvamulgund** [comment]
- [ ] **Responsiveness for screen size less than 786px**

### Testimonial Update

- Added carousel **Responsiveness remaining for screen size less than 786px** _Used Swiper Js _
- Mapped an array for data fetching.

![image](https://user-images.githubusercontent.com/63964451/184532811-3e5dbf9e-1a81-4e25-8d06-65c9a7b4f597.png)
![image](https://user-images.githubusercontent.com/63964451/184532823-98484d54-65c8-4145-bcd2-2173cca6d85a.png)
![image](https://user-images.githubusercontent.com/63964451/184532842-78e5273c-43ff-4786-b52b-7a15a72d29cd.png)
![image ](https://user-images.githubusercontent.com/63964451/184532853-47975748-84d5-4dcc-b656-ac8e963ca750.png)

- Tired with breakpoints to make it responsive but the next card is not displayed
