### ISSUE TITLE
Event Cards on Homepage

### ISSUE THREAD

**Issue by anitsingh367** [anitsingh367/LT-react-revamp#59]
Homepage cards are to be put in a structure as per this design https://www.figma.com/file/kzMg2Y4R3XITupa0BQjsKP/Living-Treasure?type=design&node-id=69-473&mode=dev

**Comment by atharvamulgund** [comment]
Fixed on 21/08 Merge Request Link: https://github.com/anitsingh367/LT-react-revamp/pull/65#issue-1859838551
