### ISSUE TITLE
Modal Component

### ISSUE THREAD

**Issue by anitsingh367** [anitsingh367/LT-react-revamp#6]
- [x] Modal should have a form with input fields and a submit button
> - [x] Input Fields should have dynamic Validation 
> > - [x] Validation should only trigger on blur and form submit 
- [x] Modal should have a map to show the event location (if any)

Refer to the below designs
- https://www.figma.com/file/kzMg2Y4R3XITupa0BQjsKP/Living-Treasure?node-id=42%3A83
- https://www.figma.com/file/kzMg2Y4R3XITupa0BQjsKP/Living-Treasure?node-id=64%3A340

**Comment by Rohitdhende** [comment]
This issue has been resolved. We can close this issue.
